[package]
name = "elterago"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.12.1"
bevy_ecs_tilemap = { git = "https://github.com/StarArawn/bevy_ecs_tilemap" }
chatgpt_rs = "1.2.3"
dotenv = "0.15.0"
tokio = { version = "1.35.0", features = ["full"] }
